# Generated by Django 3.0.4 on 2020-03-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='secondname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
