# Generated by Django 3.0.4 on 2020-03-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0004_auto_20200315_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='custom_action',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
